### ISSUE TITLE
Адресное пространство данных отделено от адресного пространства команд.

### ISSUE THREAD

**Issue by mrp149** [besm6/mesm6#1]
> Адресное пространство данных отделено от адресного пространства команд. Всего имеется 32768 слов данных и 32768 слов команд. Команды доступны только для выполнения, но не для чтения-записи. Защита данных по записи отсутствует. Выполнение данных как команд невозможно.
>
Здесь есть вопрос: если нет разделения на  виртуальную память , то как будет 
а) с поддержкой старого кода? 
в) как будет работать загрузчик? 
в)  и как реализовывать *75 (т.е. как писать команды)?

**Comment by sergev** [comment]
Да как бы нет старого кода, который имело бы смысл запускать на такой машине. Ни мониторка, ни Диспак, ни ОС Дубна сюда не вписываются. Если есть осмысленные фрагменты полезного кода, написанные на Мадлене или БЕМШе - их можно будет с некоторыми усилиями скомпилировать новым ассемблером. Но в целом считается, что люди просто будут писать ардуинные приложения на Паскале с нуля.

Соответственно, нет ни загрузчика, ни *75 экстракода. Весь код прошивается из хост-компьютера и в дальнейшем не изменяется. Ровно как на Ардуино.

**Comment by mrp149** [comment]
Да, я как-то про Ардуино, не врубился сразу, нужна кросс-система, а компилировать на машине, не требуется. Закрываем.
