### ISSUE TITLE
Test for A+X, A-X, X-A

### ISSUE THREAD

**Issue by x86128** [besm6/mesm6#6]
Поясните момент:
https://github.com/besm6/mesm6/blob/392cce50fed4c59e1e7fffe93d3a95d2cb07d18a/test/a%2Bx_a-x_x-a/a%2Bx_a-x_x-a.bemsh#L5-L9

После операции вычитания на ACC будет 13(восм). Группа омега - аддитивная.
Соотв. ω = (ACC[41] != 0) , будет ω = (0 != 0) = 0 и команда uza уйдет на fail.

Либо я неправильно что-то понимаю. Эмулятор simh тоже на fail уходит.

**Comment by sergev** [comment]
В тесте нашлась ошибка: я неправильно переделал константу i65. Было так:
```
i65     конд    b'65'

d 02034 0000 0000 0000 0065
```
Правильно так:
```
i65     конд    f'65'

d 02034 0000 0000 0000 0101
```
Этот тест проходит на микро-БЭСМ. У меня есть подробная трассировка от него. Скачать можно отсюда: https://github.com/besm6/micro-besm/releases/download/v0.1/micro-besm-test-output.zip

Там длинный файл `test.trace` в 157 мегабайт. Конкретно подтест A+X, A-X, X-A начинается со строки:
```
(4279096) 00a92 00292: 01f003 ntr 0003
```
Сравнивать с мэсм6 непросто: регистр R у микро-БЭСМ имеет 32 разряда, и печатается всё в шестнадцатеричном виде. Но младшие 6 бит совпадают по смыслу.

Сумматор A имеет 64 бита, и бэсмовские 48 бит ложатся в него нетривиальным образом: в биты 63 и 58:12. Биты 62:59 заполняются единицами, биты 11:0 - нулями. Подробности здесь: https://github.com/besm6/micro-besm/wiki/BESM6-Mode-Architecture
