### ISSUE TITLE
Inter-project dependency must not occur

### ISSUE THREAD

**Issue by leobru** [besm6/mesm6#7]
make[1]: Entering directory `/.../mesm6-master/toolchain/as'
make[1]: *** No rule to make target `../microbesm/a.out.h', needed by `as.o'.  Stop.
make[1]: Leaving directory `/.../mesm6-master/toolchain/as'
make[1]: Entering directory `/.../mesm6-master/toolchain/ld'
cc -I.. -Werror   -c -o ld.o ld.c
ld.c:30:29: error: microbesm/a.out.h: No such file or directory
ld.c:31:26: error: microbesm/ar.h: No such file or directory
ld.c:32:30: error: microbesm/ranlib.h: No such file or directory

**Comment by sergev** [comment]
Да там ещё конь не валялся.

**Comment by sergev** [comment]
Я поправил, теперь собирается.
Но оно всё ещё для 64 бит.
Надо переделывать взад на 48-битное слово.
