### ISSUE TITLE
Система прерываний МЭСМ-6. Общие принципы.

### ISSUE THREAD

**Issue by x86128** [besm6/mesm6#8]
В БЭСМ-6 аппаратные прерывания двух видов - внутренние (ОпПр1, вектор 500) и внешние (ОпПр2, векотор 501).
Внутренние возникают из-за ошибок в АУ, схем защиты памяти и т.д.
Внешние возбуждаются от периферийных устройств.
Для определения причин внутренних прерываний необходимо командой РЕГ 0237 считать из главного регистра прерываний соотв. флажки и выполнить анализ. Следует, отметить, что не все биты главного регистра прерываний читаются из защелок, некоторые приходят как wire из периферийного регистра (поэтому их невозможно погасить командой РЕГ 037.
После анализа и обработки необходимо выполнить гашение битов командой РЕГ 37.
Анализ причин прерываний в случае внешнего прерывания выполняется командой УВВ 04030 и УВВ 04034. Гашение УВВ 030.

Что предлагается сделать для МЭСМ-6.

Сделать регистр isr куда будут наложением в соотв. позиции взводиться биты причин внутренних прерываний. Например, старший бит регистра будет сигнализировать о необработанных прерываниях на регистре периферийных прерываний.
Тут возникает два пути:
1) иметь один регистр ISR и кучу линий в процессор INT_0...INT_n (гасить внутренние прерывания командой РЕГ, а внешние - командой УВВ с обращением к соотв. устройству потому что они будут приходить как wire от соотв. устройств).
2) условно разделить регистры состояния прерываний на MISR (machine) и PISR (peripheral), соотв им регистры масок MIMR, PIMR и иметь только один провод в процессор ext_int = (PISR & PIMR) != 0;
Гашение MISR выполнять РЕГ, гашение PISR - УВВ к соотв. устройству (или как PISR <= PISR & acc).

Первый способ позволит сделать с помощью схемы выбора с приоритетом переход сразу на нужный вектор с обработчиком прерывания, второй экономит провода ну и как мне кажется ближе к БЭСМ-6.

По какому пути идти?

**Comment by sergev** [comment]
Изложил своё представление на Дриме: https://besm6.dreamwidth.org/3010.html
Повторю здесь для простоты.

Я предлагаю сделать контроллер прерываний для МЭСМ-6 по мотивам одной из известных ардуинной публике архитектур. Упростить и адаптировать к 48-битному слову. Из опыта разработки RTOS для этих чипов, мне лично по душе подход PIC32.

Ограничимся 48 внешними прерываниями.

Введём регистр активных прерываний РАП, отдалённый аналог бэсмовского ГРП. Единица в каком-то бите означает, что поступил соответствующий сигнал прерывания. Единица "залипает", пока не будет сброшена софтом. 

Введём регистр маски разрешённых прерываний РМРП, аналогичный бэсмовскому МГРП. Если бит маски установлен в единицу, и в регистре активных прерываний тоже стоит единица в этом бите, то на вход процессора будет подан запрос прерывания.

Выделим для этих регистров по два дополнительных адреса: "установка в 1" ии "установка в 0". Запись битовой маски по первому адресу уставливает эти биты в единицу, записо по второму адресу сбрасывает их в 0.

Введём регистр номера текущего прерывания РНП (только чтение). На каждом такте проверяем, если есть активные прерывания (РАП) и разрешены ли они (РМРП). В этом случае заносим номер самого старшего бита в РНП и активируем глобальный сигнал прерывания для процессора.

**Comment by sergev** [comment]
Примерный список внешних прерываний:
1. Таймер 0.
2. Таймер 1.
3. Блок GPIO, включая внешние сигналы прерываний.
4. Сторожевой таймер.
5. Асинхронный порт UART 0.
6. Асинхронный порт UART 1.
7. Порт SPI 0.
8. Порт SPI 1.
9. Порт I2C 0.
10. Порт I2C 1.

**Comment by sergev** [comment]
Евгений, я поправил ISR (он же РНП), чтобы он учитывал маску IEC (РМРП). Заодно слегка доработал тест PIC и включил его в общий скрипт run-all-tests.sh.

**Comment by x86128** [comment]
@sergev получилось красиво. Спасибо.
