### ISSUE TITLE
Уровни сигналов в DE10-Lite составляют 3.3-V LVTTL

### ISSUE THREAD

**Issue by x86128** [besm6/mesm6#9]
Обнаружил, что в руководстве пользователя DE10-Lite указаны уровни сигналов 3.3-V LVTTL, но в скрипте https://github.com/besm6/mesm6/blob/master/board/de10-lite/de10-lite-build.tcl указан уровень 3 вольта.
Этот файл немного для другой версии платы?

**Comment by sergev** [comment]
Нет, плата та же самая. Не помню, откуда этот скрипт возник. Надо везде заменить на 3.3-V.

**Comment by x86128** [comment]
Моя плата до местного сортировочного центра доехала. Очень надеюсь что на днях её заполучу.  
Разверну на ней сначала hello_world. Затем проверю на ней MESM6 и поправлю тут уровни, т.к. возможно еще что-то по наименованию сигналов в модуле GPIO придумаю.

**Comment by sergev** [comment]
Отлично. Чтобы запустить MESM6 на FPGA, надо будет добавить PLL и память. И разложить сигналы по внешним контактам.
